### PR TITLE
Pass stderr as reference

### LINKED ISSUE #18: stderr must not appear in the response
In a normal FactCGI request to a nonexistent scrip I got:

#### stderr:
```
Primary script unknown
```
#### stdout:
```
Status: 404 Not Found
X-Powered-By: PHP/7.1.10
Content-type: text/html; charset=UTF-8

File not found.
```

But in the raw response handled by this lib I got this in the same var.

```
Primary script unknown
Status: 404 Not Found
X-Powered-By: PHP/7.1.10
Content-type: text/html; charset=UTF-8

File not found.
```

I saw this in the Responder:

https://github.com/hoaproject/Fastcgi/blob/b741a49c0e0638ac7f43b6689fc25b563a5f6e46/Responder.php#L226-L229

But in my opinion stdout and stderr must not bu multiplexed

### PR DESCRIPTION
**Pull request by luxifer**
(Edit by @Hywan) ~~See #18~~ Fix #18.

Allow to pass a third argument to `send` which is populated with stderr stream.

### CODE REVIEW

**Comment by Hywan** [comment]
Thanks for the PR!

Hope you're OK with my proposal: Keep `getResponseContent` and add `getResponseError` —instead of using a by-reference argument.

Please test this patch for your usecase, and give me any feedback :-).

**Comment by luxifer** [comment]
This choice is good for me too! Thanks!

**Comment by Hywan** [comment]
New release will come in few weeks. Is it OK to use `master` for now for you?

**Comment by luxifer** [comment]
I'll wait for the release to update my package 😉

**Comment by luxifer** [comment]
Example usage https://github.com/wizaplace/php-fpm-status-cli
I need the status to correctly exit if it's not 200

**Comment by mnapoli** [comment]
@Hywan hi! Would it be possible to tag a release from master to get this fix?

This would help with Bref, we currently have PHP-FPM's error output mangled with the HTTP response. I did an ugly quickfix in the meantime in https://github.com/mnapoli/bref/pull/216 

Thanks!

**Pull request merged**
