### PR TITLE
Adding Multi headers Support

### PR DESCRIPTION
**Pull request by atrope**
When we want to use Lambda integration with an ALB we must also enable Multi Header in our Load Balancer.

This PR enables it and also keeps the default functionality  of non-Multi Header as the default one.

We will only process multiheaders if specified by the `$_multiHeader ` variable.

### CODE REVIEW

**Comment by Hywan** [comment]
Hello,

Thanks for the PR! Can you provide an example of a multi-headers exactly? I'm not familiar with that.

**Comment by atrope** [comment]
With multi-value headers we receive and send the headers as arrays. 
With that we can send more than one value to the same header for example we can set more than one Cookie in the same HTTP Request.

Example of Request Headers:

```

{
    "X-Powered-By": [
        "PHP/7.2.15"
    ],
    "Expires": [
        "Thu, 19 Nov 1981 08:52:00 GMT"
    ],
    "Cache-Control": [
        "no-store, no-cache, must-revalidate"
    ],
    "Pragma": [
        "no-cache"
    ],
    "Content-Type": [
        "text/html; charset=UTF-8"
    ]
}
```
Example of Response Header:
```

{
    "x-powered-by": [
        "PHP/7.2.15"
    ],
    "expires": [
        "Thu, 19 Nov 1981 08:52:00 GMT"
    ],
    "cache-control": [
        "no-store, no-cache, must-revalidate"
    ],
    "pragma": [
        "no-cache"
    ],
    "set-cookie": [
        "CloudFront-Policy=XXXXX; expires=Tue, 12-Mar-2019 04:32:19 GMT; Max-Age=43200; path=/; domain=.example.com.br",
        "CloudFront-Signature=XXXXX; expires=Tue, 12-Mar-2019 04:32:19 GMT; Max-Age=43200; path=/; domain=.example.com.br",
        "CloudFront-Key-Pair-Id=XXXXXX; expires=Tue, 12-Mar-2019 04:32:19 GMT; Max-Age=43200; path=/; domain=.example.com.br"
    ],
    "access-control-allow-origin": [
        "*.example.com.br"
    ],
    "content-type": [
        "text/html; charset=UTF-8"
    ]
}

```

With That said, we would not be able to set the 3 cookies with the default non multi header.

Was That what you asked?

**Comment by mnapoli** [comment]
Facing the same issue with multi-header support in Bref: `$this->_responseHeaders` contains HTTP response headers indexed by header name.

The practical implication of this is that an application cannot return several cookies (multiple `Set-Cookie` headers): https://github.com/mnapoli/bref/issues/213

**Comment by sandrokeil** [comment]
@Hywan You will find a detailed HTTP multi value header explanation in [PSR-7: HTTP message interfaces](https://www.php-fig.org/psr/psr-7/) too.

@atrope Is it really necessary to introduce `$_multiHeader` variable? Why not use the PSR-7 standard here?

**Comment by atrope** [comment]
@sandrokeil can you identify if the headers received are multiHeader? if we can, there is no need for the variable, i couldn't find a way to do so.

If you point me an example i will gladly update the code.

**Comment by mnapoli** [comment]
> Why not use the PSR-7 standard here?

@sandrokeil just as a FYI this project does not use PSR-7, so I'm not sure it would make sense to introduce the whole standard just for this.

**Comment by sandrokeil** [comment]
Yes, but maybe it makes sense to bring in a new major version with multi value header as standard. Otherwise apps have to translate it. But it‘s only a suggestion.

@atrope I don‘t know the hoa code, but maybe this [message parser](
https://github.com/sandrokeil/arangodb-php-client/blob/master/src/HttpHelper.php#L31) helps.

**Comment by Hywan** [comment]
Back from work and holidays, I can finally take a look at it.

**Comment by Hywan** [comment]
I made a PR https://github.com/atrope/Fastcgi/pull/1 over this PR to simplify the code. Can you review it please, and let me know if everything is OK? So that we can merge everything as soon as possible.

**Comment by atrope** [comment]
@Hywan Done!

**Comment by Hywan** [comment]
Can you test on your usecase and tell me if everything works like a charm for you please?

**Comment by atrope** [comment]
@Hywan Yes, will do it now

**Comment by atrope** [comment]
@Hywan Worked as expected, in my use case just had to update the Responder file and change the  setMultiHeader for enableMultiHeaders :+1:

**Comment by atrope** [comment]
Closing this PR  :(

**Pull request closed without merging**
